#the original source of this file can be found in tools repository change it ther
# changes in tools|csg tiggered a full rebuild
# changes in csgapps|csg-manual|csg-tutorials only trigger tools+csg+ifself

language: cpp

sudo: false

script:
  - true

branches:
  only:
  - master
  - development
  - stable
  - next

cache:
  - ccache

compiler:
  - gcc

notifications:
  email:
    - votca-commits@googlegroups.com 
